# Preet's test Packer pipeline

trigger:
- testing/20191209.1

pool:
  vmImage: 'win2019'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: InlineAzurePowershell@1
  inputs:
    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
    ConnectedServiceNameARM: 'BigBang'
    Script: 'Write-Output ''Hello world'''


