# Preet's test Packer pipeline

queue:
  name: Preets
  timeoutInMinutes: 240


trigger:
  - packer

steps:

- task: PowerShell@2
  displayName: Check Packer
  inputs:
    targetType: 'inline'
    script: |
      " ---- "
      Get-ChildItem Env: | Sort-Object Name
      " ---- "
      C:\ProgramData\chocolatey\bin\choco.exe --version
      C:\ProgramData\chocolatey\lib\packer\tools\packer.exe --version

- task: AzureCLI@2
  inputs:
    azureSubscription: 'BigBang'
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    scriptPath: '$(Build.SourcesDirectory)\helpers\GenerateResourcesAndImage.ps1'
    addSpnToEnvironment: true

  # Build machine image
  # Build a machine image using Packer, which may be used for Azure Virtual machine scale set deployment
  # - task: PackerBuild@1
  #   inputs:
  #     #templateType: 'builtin' # Options: builtin, custom
  #     #customTemplateLocation: # Required when templateType == Custom
  #     #customTemplateParameters: '{}' # Optional
  #     connectedServiceName:
  #     #isManagedImage: true
  #     #managedImageName: # Required when isManagedImage == True
  #     location:
  #     storageAccountName:
  #     azureResourceGroup:
  #     #baseImageSource: 'default' # Options: default, customVhd
  #     #baseImage: 'MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:windows' # Required when baseImageSource == Default# Options: microsoftWindowsServer:WindowsServer:2012-R2-Datacenter:Windows, microsoftWindowsServer:WindowsServer:2016-Datacenter:Windows, microsoftWindowsServer:WindowsServer:2012-Datacenter:Windows, microsoftWindowsServer:WindowsServer:2008-R2-SP1:Windows, canonical:UbuntuServer:14.04.4-LTS:Linux, canonical:UbuntuServer:16.04-LTS:Linux, redHat:RHEL:7.2:Linux, redHat:RHEL:6.8:Linux, openLogic:CentOS:7.2:Linux, openLogic:CentOS:6.8:Linux, credativ:Debian:8:Linux, credativ:Debian:7:Linux, sUSE:OpenSUSE-Leap:42.2:Linux, sUSE:SLES:12-SP2:Linux, sUSE:SLES:11-SP4:Linux
  #     #customImageUrl: # Required when baseImageSource == CustomVhd
  #     #customImageOSType: 'windows' # Required when baseImageSource == CustomVhd# Options: windows, linux
  #     packagePath:
  #     deployScriptPath:
  #     #deployScriptArguments: # Optional
  #     #additionalBuilderParameters: '{vm_size:Standard_D3_v2}' # Optional
  #     #skipTempFileCleanupDuringVMDeprovision: true # Optional
  #     #packerVersion: # Optional
  #     #imageUri: # Optional
  #     #imageId: # Optional

  # - task: PackerBuild@1
  #   inputs:
  #     templateType: 'builtin'
  #     ConnectedServiceName: 'BigBang'
  #     isManagedImage: false
  #     location: 'australiaeast'
  #     storageAccountName: 'preettest001'
  #     azureResourceGroup: 'preet-test-rg'
  #     baseImageSource: 'customVhd'
  #     customImageOSType: 'windows'
  #     packagePath: 'Deployment Package'
  #     deployScriptPath: 'Deployment script'
  #     deployScriptArguments: 'Deployment script arguments'